---

- name: "Set unique identifier"
  set_fact:
    unique_id: "-{{ demo_projectname }}"
    unique_name: "({{ demo_projectname }})"

- name: "Update the NAMESPACE* entries to be unique"
  include_tasks: namespace.yml
  with_items:
  - "{{ openshift_cluster_content }}"

- name: "Update 'namespace: ' entries with a custom filter"
  set_fact:
    openshift_cluster_content: "{{ openshift_cluster_content | update_namespace(unique_id) }}"
