---

- name: "Prepare for demo execution"
  hosts: seed-hosts
  vars:
  # - demo_hosting_api_fqdn: - e.g.: "master1.demo.example.com:8443"
  # - demo_hosting_env:      - e.g.: "demo.example.com" 
  # - demo_projectname:      - e.g.: "companyname"  
  # - demo_scm_url:          - e.g.: "https://github.com/rht-labs/infographic"
  # - demo_username:         - e.g.: "username"
  # - demo_password:         - e.g.: "password"
  # - demo_token:            - e.g.: "OpenShift token"
  - openshift_login_url: "{{ demo_hosting_api_fqdn }}"
  - openshift_user: "{{ demo_username }}"
  - openshift_token: "{{ demo_token }}"
  roles:
  - role: common
  - role: ../roles/casl-ansible/roles/openshift-defaults
  - role: ../roles/casl-ansible/roles/openshift-login

- name: "Prepare the SCM for use with this demo env"
  hosts: seed-hosts
  roles:
  - role: scm-clone
  - role: scm-tweaks 

- name: "Append the SCM inventory to apply the changes"
  hosts: seed-hosts
  roles:
  - role: append-scm-inventory

- name: "Use the Project Name to make the demo unique"
  hosts: seed-hosts
  roles:
  - role: make-demo-unique

- name: "Seed the cluster"
  vars:
    openshift_user: "{{ demo_username }}"
    openshift_token: "{{ demo_token }}"
  include: ../roles/casl-ansible/playbooks/openshift-cluster-seed.yml

- name: "Demo prep clean-up"
  hosts: seed-hosts
  roles:
  - role: cleanup

